"""Static, documented facts the dashboard shows next to its SQL numbers.

Nothing here is computed. Each constant names the file it was copied from, and
`tests/test_api_dashboard.py` asserts the figures still appear in that file, so a source change
that this module has not followed fails a test instead of silently drifting.
"""

from __future__ import annotations

# docs/learned/results/phase5/gate-s3b.md
PRECISION_PRE_GUARD = "0.786 (22/28), blind, independent"
PRECISION_POST_GUARD = "0.92 (23/25); 0.88 if one low-confidence label is wrong"
PRECISION_CAVEAT = (
    "The post-guard figure is NOT independent of the errors the guard was built from, two of its "
    "links were labelled after their scores were seen, and all labels are Claude-written pending "
    "review. The 0.90 matcher gate is not claimed as cleanly met."
)
# CLAUDE.md section 7, Phase 1: "18,585/18,703" in-scope / stored PRICE ROWS after the first two
# collection days (ADR-0025). Quoted on the status page next to the SQL recount.
PHASE1_GATE_ROWS = "18,585"
PHASE1_GATE_MIN_LISTINGS = 3000  # CLAUDE.md section 7, Phase 1 gate

PRECISION_SOURCE_DOC = "docs/learned/results/phase5/gate-s3b.md"
PRECISION_SOURCE_FIGURES = ("0.786 (22/28)", "0.92 (23/25)", "22/25 = 0.88")

MATCHER_MODEL = (
    "Fine-tuned multilingual MiniLM cross-encoder (mMiniLMv2), ONNX fp32 on CPU, "
    "incremental batch after each daily collection run"
)

PHASES = [
    ("0 Foundation", "closed"),
    ("1 Collection", "closed"),
    ("2 Normalization", "closed"),
    ("3 Matching", "closed (tie on F1: fine-tuned 0.5B LoRA vs fine-tuned cross-encoder)"),
    ("4 Demand model", "postponed (price history too short for the pre-registered rules)"),
    ("5 Decision engine", "closed (50 recommendations, 0 margin violations, with caveats)"),
    ("6 Action layer", "closed (one apply/rollback cycle, human-approved, CLI only)"),
    ("7 Production", "in progress (7a: API + dashboard running locally; 7b: deploy)"),
]

REAL_VS_SIMULATED = [
    {
        "item": "Competitor prices and promotions",
        "kind": "real",
        "detail": "Scraped daily from three Romanian pet shops.",
    },
    {
        "item": "Product matches",
        "kind": "real",
        "detail": "Produced by the fine-tuned cross-encoder; precision is a small, caveated sample.",
    },
    {
        "item": "Recommendations and rationale",
        "kind": "real",
        "detail": "Generated by an LLM from SQL numbers and retrieved policy text; the margin "
        "floor is enforced by code after the LLM answers.",
    },
    {
        "item": "Our catalogue, cost and price history",
        "kind": "simulated",
        "detail": "A mock store stands in for our shop; its 180-day history is generated.",
    },
    {
        "item": "Sales volumes",
        "kind": "simulated",
        "detail": "No retailer shares sales data, so units sold are generated.",
    },
    {
        "item": "Price elasticity",
        "kind": "placeholder",
        "detail": "Not estimated. The demand model (Phase 4) is postponed; every recommendation "
        "carries a labelled placeholder instead of a number.",
    },
    {
        "item": "Guard stress-tests",
        "kind": "simulated",
        "detail": "Some recommendation rows use deliberately perturbed competitor prices to "
        "exercise the margin guard; they are labelled as such.",
    },
]
